# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: metabase
types:
  metabase:index:Networking:
    description: The options for networking.
    type: object
    properties:
      ecsSubnetIds:
        description: The subnets to use for the Fargate task.
        type: array
        items:
          type: string
      dbSubnetIds:
        description: The subnets to use for the RDS instance.
        type: array
        items:
          type: string
      lbSubnetIds:
        description: The subnets to use for the load balancer.
        type: array
        items:
          type: string
  metabase:index:CustomDomain:
    description: Options for setting a custom domain.
    type: object
    properties:
      hostedZoneName:
        type: string
      domainName:
        type: string
resources:
  metabase:index:Metabase:
    isComponent: true
    inputProperties:
      vpcId:
        type: string
        description: The VPC to use for the Metabase cluster.
      networking:
        $ref: "#/types/metabase:index:Networking"
      domain:
        $ref: "#/types/metabase:index:CustomDomain"
      metabaseVersion:
        description: The version of Metabase to run - used as a tag on the `metabase/metabase` Dockerhub image.
        type: string
    requiredInputs: []
    properties:
      dnsName:
        type: string
        description: The DNS name for the Metabase instance.
      securityGroupId:
        type: string
        description: The security group id for the Metabase instance.
    required:
      - dnsName
      - securityGroupId

language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.Aws: 5.*
      Pulumi.Random: 4.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/pulumi/pulumi-metabase/sdk/go/metabase
  nodejs:
    dependencies:
      "@pulumi/aws": "^5.0.0"
      "@pulumi/random": "^4.0.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-aws: ">=5.0.0,<6.0.0"
      pulumi-random: ">=4.0.0,<5.0.0"
